// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://varxwdhnpmmljtgxxwjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhcnh3ZGhucG1tbGp0Z3h4d2pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzM2MTEsImV4cCI6MjA2ODUwOTYxMX0.8NoYK2zatHAGcwo9ECVM3yDPf2Mfg4xFgYxO9tgcuOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});